spring:
  profiles: demo
  application:
    name: demoservice
  boot:
    admin:
      url: http://localhost:9999/

  zipkin:
    enabled: true
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://139.196.20.35:3306/uippttest?autoreconnect=true"
    password: "uippt2017"
    username: "root"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000

flyway:
  url: jdbc:mysql://139.196.20.35:3306/mysql
  schemas: USERSERVICE
  user: "root"
  password: "uippt2017"

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false
  port: 9000


#---
#server:
#  port: 443
#  ssl:
#    key-store: keystore.p12
#    key-store-password: springboot
#    keyStoreType: PKCS12
#    keyAlias: tomcat
